// This file is auto-generated by Supabase CLI
// Run 'npm run generate-schema' to update this file with the latest database schema

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface Database {
  // Schema types will be generated here
}
