-- Retained migration version for databases where this legacy migration ran.
-- The old hard-coded test login was retired during the MCP migration.
-- New environments must provision an owner explicitly through Supabase Auth
-- and configure ZULUNINER_MCP_OWNER_IDS; do not recreate a seeded admin.
